spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: passwordEncoding

  grpc:
    server:
      port: 9000
      negotiation-type: plaintext
      reflection:
        enabled: true
