spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: passwordEncoding

  grpc:
    server:
      port: 9000
      negotiation-type: plaintext
      reflection:
        enabled: true
management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
