spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: passwordEncoding

  grpc:
    server:
      port: 9000
      negotiation-type: plaintext
      reflection:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
server:
  port: 10087

encryption:
  master-key: "1234567890123456"
jwt:
  secret: "jwt-secret-key-for-mail-processor-jwt-secret-key"