version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  # ---------------- NETWORK ----------------
  # Docker automatically creates a bridge network

  # ---------------- REDPANDA ----------------
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.1
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp 1
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
    ports:
      - "8080:8080"
      - "19092:19092"
      - "18081:18081"

  # ---------------- REDIS STACK ----------------
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_ARGS: "--appendonly yes"
    volumes:
      - redis_data:/data

  # ---------------- SCYLLADB ----------------
  scylladb:
    image: scylladb/scylla:5.4
    container_name: scylladb
    command: >
      --smp 1
      --memory 750M
      --overprovisioned 1
      --developer-mode 1
      --listen-address 0.0.0.0
      --rpc-address 0.0.0.0
      --broadcast-rpc-address 127.0.0.1
      --enable-cache 0
    ports:
      - "9042:9042"
      - "9180:9180"
    volumes:
      - scylla_data:/var/lib/scylla

  

  # ---------------- REDPANDA CONSOLE ----------------
  redpanda-console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "8088:8080"
    environment:
      KAFKA_BROKERS: redpanda:9092
      KAFKA_SCHEMAREGISTRY_ENABLED: "true"
      KAFKA_SCHEMAREGISTRY_URLS: http://redpanda:8081
      REDPANDA_ADMINAPI_ENABLED: "true"
      REDPANDA_ADMINAPI_URLS: http://redpanda:9644
    depends_on:
      - redpanda
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


volumes:
  redis_data:
  scylla_data:
  mongo_data:


