global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'authentication-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:10000']

  - job_name: 'authorization-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:12000']

  - job_name: 'resource-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:10002']

  - job_name: 'password-encoding-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9000']

  - job_name: 'mail-stream-processor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:10003']

  - job_name: 'security-event-stream-processor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:10004']

  - job_name: 'sms-stream-processor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:10005']

  - job_name: 'processed-mail-consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:10006']

  - job_name: 'processed-security-event-consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:10007']

  - job_name: 'processed-sms-consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:10008']
