global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - 'host.docker.internal:10000' # Authentication
        - 'host.docker.internal:10002' # Authorization
        - 'host.docker.internal:8082'  # Resource
        - 'host.docker.internal:10087' # passwordEncoding (HTTP)
        - 'host.docker.internal:10008' # MailStreamProcessor
        - 'host.docker.internal:10010' # SmsStreamProcessor
        - 'host.docker.internal:10012' # SecurityEventStreamProcessor
        - 'host.docker.internal:10014' # ProcessedMailConsumer
        - 'host.docker.internal:10016' # ProcessedSmsConsumer
        - 'host.docker.internal:10018' # ProcessedSecurityEventConsumer
