apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: distributed-security
data:
  KAFKA_BOOTSTRAP_SERVERS: "redpanda.default.svc.cluster.local:9092"
  REDIS_HOST: "redis-master.default.svc.cluster.local"
  REDIS_PORT: "6379"
  ZIPKIN_ENDPOINT: "http://zipkin.distributed-security.svc.cluster.local:9411/api/v2/spans"
  SCHEMA_REGISTRY_URL: "http://redpanda.default.svc.cluster.local:8081"
  ENCRYPTION_MASTER_KEY: "1234567890123456"
  JWT_ISSUER: "my-auth-service"
