apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-stream-processor
  namespace: distributed-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-stream-processor
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: mail-stream-processor
    spec:
      containers:
      - name: mail-stream-processor
        image: mail-stream-processor:latest # Replace with actual image
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: JWT_PROCESSOR_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_PROCESSOR_SECRET
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapRef:
              name: common-config
              key: KAFKA_BOOTSTRAP_SERVERS
---
apiVersion: v1
kind: Service
metadata:
  name: mail-stream-processor
  namespace: distributed-security
spec:
  selector:
    app: mail-stream-processor
  ports:
  - protocol: TCP
    port: 10008
    targetPort: 10008
