apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-encoding
  namespace: distributed-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-encoding
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: password-encoding
    spec:
      containers:
      - name: password-encoding
        image: password-encoding:latest # Replace with actual image
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 9000
          name: grpc
        - containerPort: 10087
          name: http
        envFrom:
        - configMapRef:
            name: common-config
---
apiVersion: v1
kind: Service
metadata:
  name: password-encoding
  namespace: distributed-security
spec:
  selector:
    app: password-encoding
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    name: grpc
  - protocol: TCP
    port: 10087
    targetPort: 10087
    name: http
