apiVersion: apps/v1
kind: Deployment
metadata:
  name: processed-security-event-consumer
  namespace: distributed-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processed-security-event-consumer
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: processed-security-event-consumer
    spec:
      containers:
      - name: processed-security-event-consumer
        image: processed-security-event-consumer:latest # Replace with actual image
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        envFrom:
        - configMapRef:
            name: common-config
        env:
        - name: SPRING_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_URI
        - name: JWT_PROCESSOR_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_PROCESSOR_SECRET
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapRef:
              name: common-config
              key: KAFKA_BOOTSTRAP_SERVERS
---
apiVersion: v1
kind: Service
metadata:
  name: processed-security-event-consumer
  namespace: distributed-security
spec:
  selector:
    app: processed-security-event-consumer
  ports:
  - protocol: TCP
    port: 10018
    targetPort: 10018
