apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: distributed-security
type: Opaque
stringData:
  MONGO_URI: "mongodb://admin:secret@mongo.distributed-security.svc.cluster.local:27017/security?authSource=admin"
  MONGO_AUTH_URI: "mongodb://admin:secret@mongo.distributed-security.svc.cluster.local:27017/authorization?authSource=admin"
  MONGO_PASSWORD: "secret"
  JWT_SECRET: "new-access-secret-key-new-access-secret-key"
  HMAC_OLD_KEY: "old-hmac-secret-key-old-hmac-secret-key"
  HMAC_NEW_KEY: "new-hmac-secret-key-new-hmac-secret-key"
  ACCESS_OLD_KEY: "old-access-secret-key-old-access-secret-key"
  ACCESS_NEW_KEY: "new-access-secret-key-new-access-secret-key"
  REFRESH_OLD_KEY: "old-refresh-secret-key-old-refresh-secret-key"
  REFRESH_NEW_KEY: "new-refresh-secret-key-new-refresh-secret-key"
  TEMP_OLD_KEY: "old-temp-secret-key-old-temp-secret-key"
  TEMP_NEW_KEY: "new-temp-secret-key-new-temp-secret-key"
  FIDO_OLD_KEY: "fido-old-hmac-secret-key-fido-old-hmac-secret-key"
  FIDO_NEW_KEY: "fido-new-hmac-secret-key-fido-new-hmac-secret-key"
  JWT_PROCESSOR_SECRET: "jwt-secret-key-for-mail-processor-jwt-secret-key"
