syntax = "proto3";

package one.org.security.passwordEncoding;

option java_multiple_files = true;
option java_package = "one.org.security.passwordEncoding";
option java_outer_classname = "PasswordEncodingProto";

service PasswordEncodingService {
  rpc Encode (EncodeRequest) returns (EncodeResponse);
  rpc Verify (VerifyRequest) returns (VerifyResponse);
}

message EncodeRequest {
  string password = 1;
}

message EncodeResponse {
  string encoded_password = 1;
}

message VerifyRequest {
  string password = 1;
  string encoded_password = 2;
}

message VerifyResponse {
  bool result = 1;
}
