package one.org.security.common.enums;

public enum Event {
    REGISTER,
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    QR_LOGIN_SUCCESS,
    QR_LOGIN_FAIL,
    FIDO_REGISTER_SUCCESS,
    FIDO_REGISTER_FAIL,
    FIDO_LOGIN_SUCCESS,
    FIDO_LOGIN_FAIL,
    FORGET_PASSWORD_SUCCESS,
    FORGET_PASSWORD_FAIL,
    FORGET_PASSWORD_INITIATED,
    PASSWORD_CHANGED,
    BACKUP_EMAIL_VERIFIED,
    PHONE_NUMBER_VERIFIED,
    ACCOUNT_LOCKED,
    LOGOUT,
    ACCOUNT_DELETED,
    AUTHERIZED_CLIENT,
    CLIENT_ACCOUNT_CREATED,
    CLIENT_ACCOUNT_DELETED
}
