apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: distributed-security-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/rahulgupta/distributedSecurity.git" # Replace with actual repo URL
    targetRevision: HEAD
    path: k8s
  destination:
    server: "https://kubernetes.default.svc"
    namespace: distributed-security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
