/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package one.org.security.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProcessedSecurityEventLog extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7677501977919262115L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProcessedSecurityEventLog\",\"namespace\":\"one.org.security.avro\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"processedAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"securityEvents\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"SecurityEventLog\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"user\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"deviceHash\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"ipAddress\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"event\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"message\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<ProcessedSecurityEventLog> ENCODER =
      new BinaryMessageEncoder<ProcessedSecurityEventLog>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProcessedSecurityEventLog> DECODER =
      new BinaryMessageDecoder<ProcessedSecurityEventLog>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProcessedSecurityEventLog> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProcessedSecurityEventLog> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProcessedSecurityEventLog> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ProcessedSecurityEventLog>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProcessedSecurityEventLog to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProcessedSecurityEventLog from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProcessedSecurityEventLog instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProcessedSecurityEventLog fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.time.Instant processedAt;
  private java.util.List<one.org.security.avro.SecurityEventLog> securityEvents;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProcessedSecurityEventLog() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param processedAt The new value for processedAt
   * @param securityEvents The new value for securityEvents
   */
  public ProcessedSecurityEventLog(java.lang.String id, java.time.Instant processedAt, java.util.List<one.org.security.avro.SecurityEventLog> securityEvents) {
    this.id = id;
    this.processedAt = processedAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.securityEvents = securityEvents;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return processedAt;
    case 2: return securityEvents;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: processedAt = (java.time.Instant)value$; break;
    case 2: securityEvents = (java.util.List<one.org.security.avro.SecurityEventLog>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'processedAt' field.
   * @return The value of the 'processedAt' field.
   */
  public java.time.Instant getProcessedAt() {
    return processedAt;
  }


  /**
   * Sets the value of the 'processedAt' field.
   * @param value the value to set.
   */
  public void setProcessedAt(java.time.Instant value) {
    this.processedAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'securityEvents' field.
   * @return The value of the 'securityEvents' field.
   */
  public java.util.List<one.org.security.avro.SecurityEventLog> getSecurityEvents() {
    return securityEvents;
  }


  /**
   * Sets the value of the 'securityEvents' field.
   * @param value the value to set.
   */
  public void setSecurityEvents(java.util.List<one.org.security.avro.SecurityEventLog> value) {
    this.securityEvents = value;
  }

  /**
   * Creates a new ProcessedSecurityEventLog RecordBuilder.
   * @return A new ProcessedSecurityEventLog RecordBuilder
   */
  public static one.org.security.avro.ProcessedSecurityEventLog.Builder newBuilder() {
    return new one.org.security.avro.ProcessedSecurityEventLog.Builder();
  }

  /**
   * Creates a new ProcessedSecurityEventLog RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProcessedSecurityEventLog RecordBuilder
   */
  public static one.org.security.avro.ProcessedSecurityEventLog.Builder newBuilder(one.org.security.avro.ProcessedSecurityEventLog.Builder other) {
    if (other == null) {
      return new one.org.security.avro.ProcessedSecurityEventLog.Builder();
    } else {
      return new one.org.security.avro.ProcessedSecurityEventLog.Builder(other);
    }
  }

  /**
   * Creates a new ProcessedSecurityEventLog RecordBuilder by copying an existing ProcessedSecurityEventLog instance.
   * @param other The existing instance to copy.
   * @return A new ProcessedSecurityEventLog RecordBuilder
   */
  public static one.org.security.avro.ProcessedSecurityEventLog.Builder newBuilder(one.org.security.avro.ProcessedSecurityEventLog other) {
    if (other == null) {
      return new one.org.security.avro.ProcessedSecurityEventLog.Builder();
    } else {
      return new one.org.security.avro.ProcessedSecurityEventLog.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProcessedSecurityEventLog instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProcessedSecurityEventLog>
    implements org.apache.avro.data.RecordBuilder<ProcessedSecurityEventLog> {

    private java.lang.String id;
    private java.time.Instant processedAt;
    private java.util.List<one.org.security.avro.SecurityEventLog> securityEvents;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(one.org.security.avro.ProcessedSecurityEventLog.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.processedAt)) {
        this.processedAt = data().deepCopy(fields()[1].schema(), other.processedAt);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.securityEvents)) {
        this.securityEvents = data().deepCopy(fields()[2].schema(), other.securityEvents);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ProcessedSecurityEventLog instance
     * @param other The existing instance to copy.
     */
    private Builder(one.org.security.avro.ProcessedSecurityEventLog other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.processedAt)) {
        this.processedAt = data().deepCopy(fields()[1].schema(), other.processedAt);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.securityEvents)) {
        this.securityEvents = data().deepCopy(fields()[2].schema(), other.securityEvents);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public one.org.security.avro.ProcessedSecurityEventLog.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public one.org.security.avro.ProcessedSecurityEventLog.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'processedAt' field.
      * @return The value.
      */
    public java.time.Instant getProcessedAt() {
      return processedAt;
    }


    /**
      * Sets the value of the 'processedAt' field.
      * @param value The value of 'processedAt'.
      * @return This builder.
      */
    public one.org.security.avro.ProcessedSecurityEventLog.Builder setProcessedAt(java.time.Instant value) {
      validate(fields()[1], value);
      this.processedAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'processedAt' field has been set.
      * @return True if the 'processedAt' field has been set, false otherwise.
      */
    public boolean hasProcessedAt() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'processedAt' field.
      * @return This builder.
      */
    public one.org.security.avro.ProcessedSecurityEventLog.Builder clearProcessedAt() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'securityEvents' field.
      * @return The value.
      */
    public java.util.List<one.org.security.avro.SecurityEventLog> getSecurityEvents() {
      return securityEvents;
    }


    /**
      * Sets the value of the 'securityEvents' field.
      * @param value The value of 'securityEvents'.
      * @return This builder.
      */
    public one.org.security.avro.ProcessedSecurityEventLog.Builder setSecurityEvents(java.util.List<one.org.security.avro.SecurityEventLog> value) {
      validate(fields()[2], value);
      this.securityEvents = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'securityEvents' field has been set.
      * @return True if the 'securityEvents' field has been set, false otherwise.
      */
    public boolean hasSecurityEvents() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'securityEvents' field.
      * @return This builder.
      */
    public one.org.security.avro.ProcessedSecurityEventLog.Builder clearSecurityEvents() {
      securityEvents = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProcessedSecurityEventLog build() {
      try {
        ProcessedSecurityEventLog record = new ProcessedSecurityEventLog();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.processedAt = fieldSetFlags()[1] ? this.processedAt : (java.time.Instant) defaultValue(fields()[1]);
        record.securityEvents = fieldSetFlags()[2] ? this.securityEvents : (java.util.List<one.org.security.avro.SecurityEventLog>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProcessedSecurityEventLog>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProcessedSecurityEventLog>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProcessedSecurityEventLog>
    READER$ = (org.apache.avro.io.DatumReader<ProcessedSecurityEventLog>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










