/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package one.org.security.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProcessedMail extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5163835490026012903L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProcessedMail\",\"namespace\":\"one.org.security.avro\",\"fields\":[{\"name\":\"mails\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Mail\",\"fields\":[{\"name\":\"to\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"subject\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"body\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProcessedMail> ENCODER =
      new BinaryMessageEncoder<ProcessedMail>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProcessedMail> DECODER =
      new BinaryMessageDecoder<ProcessedMail>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProcessedMail> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProcessedMail> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProcessedMail> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ProcessedMail>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProcessedMail to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProcessedMail from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProcessedMail instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProcessedMail fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.List<one.org.security.avro.Mail> mails;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProcessedMail() {}

  /**
   * All-args constructor.
   * @param mails The new value for mails
   */
  public ProcessedMail(java.util.List<one.org.security.avro.Mail> mails) {
    this.mails = mails;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return mails;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: mails = (java.util.List<one.org.security.avro.Mail>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'mails' field.
   * @return The value of the 'mails' field.
   */
  public java.util.List<one.org.security.avro.Mail> getMails() {
    return mails;
  }


  /**
   * Sets the value of the 'mails' field.
   * @param value the value to set.
   */
  public void setMails(java.util.List<one.org.security.avro.Mail> value) {
    this.mails = value;
  }

  /**
   * Creates a new ProcessedMail RecordBuilder.
   * @return A new ProcessedMail RecordBuilder
   */
  public static one.org.security.avro.ProcessedMail.Builder newBuilder() {
    return new one.org.security.avro.ProcessedMail.Builder();
  }

  /**
   * Creates a new ProcessedMail RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProcessedMail RecordBuilder
   */
  public static one.org.security.avro.ProcessedMail.Builder newBuilder(one.org.security.avro.ProcessedMail.Builder other) {
    if (other == null) {
      return new one.org.security.avro.ProcessedMail.Builder();
    } else {
      return new one.org.security.avro.ProcessedMail.Builder(other);
    }
  }

  /**
   * Creates a new ProcessedMail RecordBuilder by copying an existing ProcessedMail instance.
   * @param other The existing instance to copy.
   * @return A new ProcessedMail RecordBuilder
   */
  public static one.org.security.avro.ProcessedMail.Builder newBuilder(one.org.security.avro.ProcessedMail other) {
    if (other == null) {
      return new one.org.security.avro.ProcessedMail.Builder();
    } else {
      return new one.org.security.avro.ProcessedMail.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProcessedMail instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProcessedMail>
    implements org.apache.avro.data.RecordBuilder<ProcessedMail> {

    private java.util.List<one.org.security.avro.Mail> mails;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(one.org.security.avro.ProcessedMail.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.mails)) {
        this.mails = data().deepCopy(fields()[0].schema(), other.mails);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing ProcessedMail instance
     * @param other The existing instance to copy.
     */
    private Builder(one.org.security.avro.ProcessedMail other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.mails)) {
        this.mails = data().deepCopy(fields()[0].schema(), other.mails);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'mails' field.
      * @return The value.
      */
    public java.util.List<one.org.security.avro.Mail> getMails() {
      return mails;
    }


    /**
      * Sets the value of the 'mails' field.
      * @param value The value of 'mails'.
      * @return This builder.
      */
    public one.org.security.avro.ProcessedMail.Builder setMails(java.util.List<one.org.security.avro.Mail> value) {
      validate(fields()[0], value);
      this.mails = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'mails' field has been set.
      * @return True if the 'mails' field has been set, false otherwise.
      */
    public boolean hasMails() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'mails' field.
      * @return This builder.
      */
    public one.org.security.avro.ProcessedMail.Builder clearMails() {
      mails = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProcessedMail build() {
      try {
        ProcessedMail record = new ProcessedMail();
        record.mails = fieldSetFlags()[0] ? this.mails : (java.util.List<one.org.security.avro.Mail>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProcessedMail>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProcessedMail>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProcessedMail>
    READER$ = (org.apache.avro.io.DatumReader<ProcessedMail>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.mails.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (one.org.security.avro.Mail e0: this.mails) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<one.org.security.avro.Mail> a0 = this.mails;
      if (a0 == null) {
        a0 = new SpecificData.Array<one.org.security.avro.Mail>((int)size0, SCHEMA$.getField("mails").schema());
        this.mails = a0;
      } else a0.clear();
      SpecificData.Array<one.org.security.avro.Mail> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<one.org.security.avro.Mail>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          one.org.security.avro.Mail e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new one.org.security.avro.Mail();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<one.org.security.avro.Mail> a0 = this.mails;
          if (a0 == null) {
            a0 = new SpecificData.Array<one.org.security.avro.Mail>((int)size0, SCHEMA$.getField("mails").schema());
            this.mails = a0;
          } else a0.clear();
          SpecificData.Array<one.org.security.avro.Mail> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<one.org.security.avro.Mail>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              one.org.security.avro.Mail e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new one.org.security.avro.Mail();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










