/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package one.org.security.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SecurityEventLog extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7127046757986704173L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SecurityEventLog\",\"namespace\":\"one.org.security.avro\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"user\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"deviceHash\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"ipAddress\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"event\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"message\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<SecurityEventLog> ENCODER =
      new BinaryMessageEncoder<SecurityEventLog>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SecurityEventLog> DECODER =
      new BinaryMessageDecoder<SecurityEventLog>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SecurityEventLog> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SecurityEventLog> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SecurityEventLog> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SecurityEventLog>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SecurityEventLog to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SecurityEventLog from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SecurityEventLog instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SecurityEventLog fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String user;
  private java.lang.String deviceHash;
  private java.lang.String ipAddress;
  private java.lang.String event;
  private java.lang.String message;
  private java.time.Instant createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SecurityEventLog() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param user The new value for user
   * @param deviceHash The new value for deviceHash
   * @param ipAddress The new value for ipAddress
   * @param event The new value for event
   * @param message The new value for message
   * @param createdAt The new value for createdAt
   */
  public SecurityEventLog(java.lang.String id, java.lang.String user, java.lang.String deviceHash, java.lang.String ipAddress, java.lang.String event, java.lang.String message, java.time.Instant createdAt) {
    this.id = id;
    this.user = user;
    this.deviceHash = deviceHash;
    this.ipAddress = ipAddress;
    this.event = event;
    this.message = message;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return user;
    case 2: return deviceHash;
    case 3: return ipAddress;
    case 4: return event;
    case 5: return message;
    case 6: return createdAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: user = value$ != null ? value$.toString() : null; break;
    case 2: deviceHash = value$ != null ? value$.toString() : null; break;
    case 3: ipAddress = value$ != null ? value$.toString() : null; break;
    case 4: event = value$ != null ? value$.toString() : null; break;
    case 5: message = value$ != null ? value$.toString() : null; break;
    case 6: createdAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'user' field.
   * @return The value of the 'user' field.
   */
  public java.lang.String getUser() {
    return user;
  }


  /**
   * Sets the value of the 'user' field.
   * @param value the value to set.
   */
  public void setUser(java.lang.String value) {
    this.user = value;
  }

  /**
   * Gets the value of the 'deviceHash' field.
   * @return The value of the 'deviceHash' field.
   */
  public java.lang.String getDeviceHash() {
    return deviceHash;
  }


  /**
   * Sets the value of the 'deviceHash' field.
   * @param value the value to set.
   */
  public void setDeviceHash(java.lang.String value) {
    this.deviceHash = value;
  }

  /**
   * Gets the value of the 'ipAddress' field.
   * @return The value of the 'ipAddress' field.
   */
  public java.lang.String getIpAddress() {
    return ipAddress;
  }


  /**
   * Sets the value of the 'ipAddress' field.
   * @param value the value to set.
   */
  public void setIpAddress(java.lang.String value) {
    this.ipAddress = value;
  }

  /**
   * Gets the value of the 'event' field.
   * @return The value of the 'event' field.
   */
  public java.lang.String getEvent() {
    return event;
  }


  /**
   * Sets the value of the 'event' field.
   * @param value the value to set.
   */
  public void setEvent(java.lang.String value) {
    this.event = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.String getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.String value) {
    this.message = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new SecurityEventLog RecordBuilder.
   * @return A new SecurityEventLog RecordBuilder
   */
  public static one.org.security.avro.SecurityEventLog.Builder newBuilder() {
    return new one.org.security.avro.SecurityEventLog.Builder();
  }

  /**
   * Creates a new SecurityEventLog RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SecurityEventLog RecordBuilder
   */
  public static one.org.security.avro.SecurityEventLog.Builder newBuilder(one.org.security.avro.SecurityEventLog.Builder other) {
    if (other == null) {
      return new one.org.security.avro.SecurityEventLog.Builder();
    } else {
      return new one.org.security.avro.SecurityEventLog.Builder(other);
    }
  }

  /**
   * Creates a new SecurityEventLog RecordBuilder by copying an existing SecurityEventLog instance.
   * @param other The existing instance to copy.
   * @return A new SecurityEventLog RecordBuilder
   */
  public static one.org.security.avro.SecurityEventLog.Builder newBuilder(one.org.security.avro.SecurityEventLog other) {
    if (other == null) {
      return new one.org.security.avro.SecurityEventLog.Builder();
    } else {
      return new one.org.security.avro.SecurityEventLog.Builder(other);
    }
  }

  /**
   * RecordBuilder for SecurityEventLog instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SecurityEventLog>
    implements org.apache.avro.data.RecordBuilder<SecurityEventLog> {

    private java.lang.String id;
    private java.lang.String user;
    private java.lang.String deviceHash;
    private java.lang.String ipAddress;
    private java.lang.String event;
    private java.lang.String message;
    private java.time.Instant createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(one.org.security.avro.SecurityEventLog.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.user)) {
        this.user = data().deepCopy(fields()[1].schema(), other.user);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.deviceHash)) {
        this.deviceHash = data().deepCopy(fields()[2].schema(), other.deviceHash);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[3].schema(), other.ipAddress);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.event)) {
        this.event = data().deepCopy(fields()[4].schema(), other.event);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.message)) {
        this.message = data().deepCopy(fields()[5].schema(), other.message);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[6].schema(), other.createdAt);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing SecurityEventLog instance
     * @param other The existing instance to copy.
     */
    private Builder(one.org.security.avro.SecurityEventLog other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.user)) {
        this.user = data().deepCopy(fields()[1].schema(), other.user);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.deviceHash)) {
        this.deviceHash = data().deepCopy(fields()[2].schema(), other.deviceHash);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[3].schema(), other.ipAddress);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.event)) {
        this.event = data().deepCopy(fields()[4].schema(), other.event);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.message)) {
        this.message = data().deepCopy(fields()[5].schema(), other.message);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[6].schema(), other.createdAt);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public one.org.security.avro.SecurityEventLog.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public one.org.security.avro.SecurityEventLog.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'user' field.
      * @return The value.
      */
    public java.lang.String getUser() {
      return user;
    }


    /**
      * Sets the value of the 'user' field.
      * @param value The value of 'user'.
      * @return This builder.
      */
    public one.org.security.avro.SecurityEventLog.Builder setUser(java.lang.String value) {
      validate(fields()[1], value);
      this.user = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'user' field has been set.
      * @return True if the 'user' field has been set, false otherwise.
      */
    public boolean hasUser() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'user' field.
      * @return This builder.
      */
    public one.org.security.avro.SecurityEventLog.Builder clearUser() {
      user = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'deviceHash' field.
      * @return The value.
      */
    public java.lang.String getDeviceHash() {
      return deviceHash;
    }


    /**
      * Sets the value of the 'deviceHash' field.
      * @param value The value of 'deviceHash'.
      * @return This builder.
      */
    public one.org.security.avro.SecurityEventLog.Builder setDeviceHash(java.lang.String value) {
      validate(fields()[2], value);
      this.deviceHash = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceHash' field has been set.
      * @return True if the 'deviceHash' field has been set, false otherwise.
      */
    public boolean hasDeviceHash() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'deviceHash' field.
      * @return This builder.
      */
    public one.org.security.avro.SecurityEventLog.Builder clearDeviceHash() {
      deviceHash = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ipAddress' field.
      * @return The value.
      */
    public java.lang.String getIpAddress() {
      return ipAddress;
    }


    /**
      * Sets the value of the 'ipAddress' field.
      * @param value The value of 'ipAddress'.
      * @return This builder.
      */
    public one.org.security.avro.SecurityEventLog.Builder setIpAddress(java.lang.String value) {
      validate(fields()[3], value);
      this.ipAddress = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ipAddress' field has been set.
      * @return True if the 'ipAddress' field has been set, false otherwise.
      */
    public boolean hasIpAddress() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ipAddress' field.
      * @return This builder.
      */
    public one.org.security.avro.SecurityEventLog.Builder clearIpAddress() {
      ipAddress = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'event' field.
      * @return The value.
      */
    public java.lang.String getEvent() {
      return event;
    }


    /**
      * Sets the value of the 'event' field.
      * @param value The value of 'event'.
      * @return This builder.
      */
    public one.org.security.avro.SecurityEventLog.Builder setEvent(java.lang.String value) {
      validate(fields()[4], value);
      this.event = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'event' field has been set.
      * @return True if the 'event' field has been set, false otherwise.
      */
    public boolean hasEvent() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'event' field.
      * @return This builder.
      */
    public one.org.security.avro.SecurityEventLog.Builder clearEvent() {
      event = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.String getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public one.org.security.avro.SecurityEventLog.Builder setMessage(java.lang.String value) {
      validate(fields()[5], value);
      this.message = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public one.org.security.avro.SecurityEventLog.Builder clearMessage() {
      message = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public one.org.security.avro.SecurityEventLog.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[6], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public one.org.security.avro.SecurityEventLog.Builder clearCreatedAt() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SecurityEventLog build() {
      try {
        SecurityEventLog record = new SecurityEventLog();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.user = fieldSetFlags()[1] ? this.user : (java.lang.String) defaultValue(fields()[1]);
        record.deviceHash = fieldSetFlags()[2] ? this.deviceHash : (java.lang.String) defaultValue(fields()[2]);
        record.ipAddress = fieldSetFlags()[3] ? this.ipAddress : (java.lang.String) defaultValue(fields()[3]);
        record.event = fieldSetFlags()[4] ? this.event : (java.lang.String) defaultValue(fields()[4]);
        record.message = fieldSetFlags()[5] ? this.message : (java.lang.String) defaultValue(fields()[5]);
        record.createdAt = fieldSetFlags()[6] ? this.createdAt : (java.time.Instant) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SecurityEventLog>
    WRITER$ = (org.apache.avro.io.DatumWriter<SecurityEventLog>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SecurityEventLog>
    READER$ = (org.apache.avro.io.DatumReader<SecurityEventLog>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










