spring:
  application:
    name: Autherization
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  mongodb:
    uri: mongodb://admin:secret@localhost:27017/security?authSource=admin
oauth2:
  server:
    issuer: http://localhost:12000
  keys:
    key-id: "key-id"
    private-key: |
      -----BEGIN PRIVATE KEY-----
      MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg+qVKjM024FRnAg1q
      qlztqkkZFgotRJYCi6sI47iAW/uhRANCAARWGNUcLum0dlsfBjrHMAwZA6JQZZO9
      eQ83XaifV3YYj7VnBWQ5DKathXyyJcn/wUHAfU1N4dXhkhUywqCHtE5U
      -----END PRIVATE KEY-----
server:
  port: 12000
hmac:
  oldkeyId: "hmac-key-2025-12"
  newkeyId: "hmac-key-2026-01"
  oldkey: "old-hmac-secret-key-old-hmac-secret-key"
  newkey: "new-hmac-secret-key-new-hmac-secret-key"
grpc:
  client:
    password-encoding-service:
      address: "static://localhost:9000"
      negotiation-type: plaintext
