spring:
  application:
    name: Autherization
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://admin:secret@localhost:27017/security?authSource=admin
oauth2:
  server:
    issuer: http://localhost:12000
  keys:
    current:
      key-id: "rsa-key-current"
      private-key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCcOwqT0p/Zf0AW
        rI+PL1yL8kSzW58HCzsfGZi2LLEVpA5rGU88PL/QqjNhHdorkUz4iPfiEhUyCCyW
        PjqBxLZpccZtL006yVtNPKCVZtbB020S1lD9u2MHB7JXU9Mfr5h7gXO4ZiTPFNE6
        LpUbOWQVvmvUZ4OqpnjghmvvMGja0Jb06XGqGP75mc53oRqsCKwzjn2dU5vMmcvW
        Jv0NvkUutnLJImrFUCznjZ4InTDVPTgPmIWxtMZuor+rl/nhoeJbxnnSa2UoSggd
        hW+pT5904wCxbVH9A0B/eclXeR7jRNB1rgMNVCUyaiDoXoJmdwfySRyEML3GH1gY
        3/NsJgvtAgMBAAECggEAE7p27aTOz7nRyis0nl8GNPE9JgMKCWsse5MRZYvY5C6J
        LZK5c+td84fSoM8SvPwGYr91F09eQtOlFxHjnyh2j8kwxpqPCj82xYGZllQxXAeK
        rLLIm8nnyZGkvoH/f+7+ITZ/JPLXxMNQX88AauWBPdJZLoN7LSJZfaIr4L1VuFp6
        o41ol+j9mC0rSK94vaa/UJPjXFHMw3EJfggjBqzZySKbSU62y1lt+vPoG7eMFZx+
        WhWSs5a6XjaOLwxVy1iPPotHYQKK6dCTu6qNcZEy8HFQAvV7961ixCCaVjows87o
        GKZWcMeEseNmekdpG3mWY8/qxBOzXdC/26D1iIs6VwKBgQDL9J56IunmbUyv0DZz
        DW+aM/Mn847KiJPvdfCa6d1NCtWnnoEDuM4lzFA3FQWnUUet/Z2m+a6kv6ax2P25
        Ui+pI6YsQ6LV7s2chJp5VU/ZGQJKOUzrAQG54xq1xWYjHkZEeP64N2xyjcrlWbSf
        3hmaV/ELqRXNgLimHYkTibmaLwKBgQDEGMu6XjHOvahf5voYbMEUH3D6dGNhM6zz
        Kp8UuYc83UfwPi+AoPyWDwJZLAkW9Cb+I/G9rpyvm6SrkymiMORv8pZLuUcxawv9
        wWae0vNhcclNf592suDxwOhoFLM4ix/ylMqqZpuaNBAFJm6C/OvZkaHEez0GGBnH
        bsiQvb0gowKBgEm2YUh3Md4MBrlMIUG3y2wJ9omr5yGf9weGsqzqdQcRMWLhUHON
        6UOT8jHWMTLll2h0zvO4LbxxX8fLSvgdkggpUDeTQljbdAhrjIDpqnAmL8OvrfMJ
        bBxIzjB/5YgvuumoaTcfINzODlSR9UwKM2qq+f1i4PRi31l6Nz6OejwVAoGBAKYN
        eTbv3K183L+ZD97u+PDZTwpG1IDTCXlAdkVOdb6MgwZlIkSCDmHjg9GPAIN3bC14
        spQ08GmkGuVPUMoPLOG/QpYM5sRqKVVQGF4VtBKoEBaYI6iYAPO2rxazsLAI35zD
        cnqpOMpzm71AtgQluHIcaCfBVAN9FRdUMHKguS6RAoGANbXBYmn1aNxUiX17peiC
        tct0oayciV2ACPjVyhT87TX/oHzwGbe9Q0GXg49bFIeZxEN4ToTOdTl0ha4Jt8qG
        IgGedcBVBt5uJkQGRWHGdsFj9G28Bjo+t0PdGfylDxB7RVobdKO3XGu+H4wvqQZp
        JLRtBscWyr6sHDC/em6cQQY=
        -----END PRIVATE KEY-----
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnDsKk9Kf2X9AFqyPjy9c
        i/JEs1ufBws7HxmYtiyxFaQOaxlPPDy/0KozYR3aK5FM+Ij34hIVMggslj46gcS2
        aXHGbS9NOslbTTyglWbWwdNtEtZQ/btjBweyV1PTH6+Ye4FzuGYkzxTROi6VGzlk
        Fb5r1GeDqqZ44IZr7zBo2tCW9Olxqhj++ZnOd6EarAisM459nVObzJnL1ib9Db5F
        LrZyySJqxVAs542eCJ0w1T04D5iFsbTGbqK/q5f54aHiW8Z50mtlKEoIHYVvqU+f
        dOMAsW1R/QNAf3nJV3ke40TQda4DDVQlMmog6F6CZncH8kkchDC9xh9YGN/zbCYL
        7QIDAQAB
        -----END PUBLIC KEY-----
    old:
      key-id: "rsa-key-old"
      private-key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCptzEXOvagHPBE
        1Tcr76tuoUBAwXGFWKFdp3h8mTnxEoCHFvhWE3EdZrD4dr/F1D5eo8qr7O75nfNr
        TD2yhnQsJT5OLRlE/ADAZ5FFUn9StI1Jbxj3ZJmK4LqT4j+1MjpZJLmZYrUL+ptv
        phGbF3o2FLkGVKzYJYzvsAI756kKoejGTduoVGH60GaAtBmDx74zkP9894+LMum7
        T5SFdkKhy3q0AYK3nuod55kWWBDEubZUl4vWQ1FWn5AvQEJUboMkn2crf9c+0VrP
        JgkC8ceS5dVtR0wx9bfCml7WycqMx/jOtvSpPzAJZzdTfO2l3YAnnT+6Ax+v2yDf
        8MV4yb6VAgMBAAECggEAAY3lWY8UTF9Axv4vLLadI6xQ9v0uix8f5SeZB836Lp/F
        4d2JR3YEJOS0w5PPw0TgoazbtclZjuLQYAnrZWHqhZehHvhfw8QfMyzTu/AbfZcl
        djJkVPfHh7FW7uL4PrJsJRjgjUmWVNuUODdwSVmqqHoFA+oeNoPBzW1QJeDJ8NLM
        ReOlj1nB1TcPtvDXRTOCaK6zCgy1iwLH78FYE1vHSPHWG9EXJwyZ6b7oBoCjf+AQ
        XSay9yR3+sMPlFwIonlAuOKEGqOLE/dVAe30XeGz/kmubwKZmi+ZubaDwo0cAvNE
        4DXYCe5v7CRduZZYsMowNH9F+yBI9gQ+6J/rQYQgEwKBgQDg+Q+BPzTloEKHV9xQ
        u8LZnTeNDW1F81fEtvtzDrYeuIgh+HP6BKad+zP4ndnWkPjBQAQLjYlkq+6q+rt2
        U1F678XJQrhnzkyWz7OHCKwegziB4HWNptBtHYofDYHw6/Cvq7qpZvJFH1faztRc
        P2klpqb5VyCi2TSDFp71mRP7owKBgQDBHzSeiXQMUrao5UOx1IRcxV6wYlN0R+mt
        yE1HfLHjwLYQeax+uavU1oZVikcV6WgwAMP00rSx0mUvY+OkVZLq74b4QHyB4BVp
        8Z3CEi/zcwSSEYs68obH2u+7DItDmr/688pZQGvMiaGcyOlwrFUcNhsfzcFECVMB
        JJXaqzqAZwKBgG5VF2qOohWfpCEWUOFzRBtPhGfz1syAjGHYT7dc1qp4W6M1Y0OR
        tlkyUomyeJxHWwgDqjg0QNaTj6hg8UEVmZdOMlUDGMcoIN2xnV0zPp50QmlHuL8w
        uXVaEFwsVrbeL5soAJKF/3kw5vhTiUh4fMvPUIJmXYYgOiW0GV9fpLI7AoGAEGzd
        Btbd/eZTDs5hEZDnqRRIV2wlePBc2aD9oaTjZGGRmpkeqLCWAsY0KrZWEXEGoX6P
        LBV3tOAWJw+x3tpAYqb4rcieTlWGvLoGFumBFo2jx+CiHONfv0PJu/j3J0rUJT3y
        6eBmysCx9CnKYQDnRDz91ZikZWr9mk1ISY7irOUCgYEA2uJ4/VGaSJAbVG4/t4yT
        bfrClSTzBmBoMOo/tWs8I05DFwqJw5A3ds0BeVLLL0Tt0EIKq7j10PpbegGx7AJn
        v6iIpAlWgwSbR2V3j84m6ky/J9P2M9jiesB05yfqTN2jOow69+K34pma+bKdWl9I
        U4h1JZSK14TYfA51iHV8HvQ=
        -----END PRIVATE KEY-----
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqbcxFzr2oBzwRNU3K++r
        bqFAQMFxhVihXad4fJk58RKAhxb4VhNxHWaw+Ha/xdQ+XqPKq+zu+Z3za0w9soZ0
        LCU+Ti0ZRPwAwGeRRVJ/UrSNSW8Y92SZiuC6k+I/tTI6WSS5mWK1C/qbb6YRmxd6
        NhS5BlSs2CWM77ACO+epCqHoxk3bqFRh+tBmgLQZg8e+M5D/fPePizLpu0+UhXZC
        oct6tAGCt57qHeeZFlgQxLm2VJeL1kNRVp+QL0BCVG6DJJ9nK3/XPtFazyYJAvHH
        kuXVbUdMMfW3wppe1snKjMf4zrb0qT8wCWc3U3ztpd2AJ50/ugMfr9sg3/DFeMm+
        lQIDAQAB
        -----END PUBLIC KEY-----
server:
  port: 12000
hmac:
  oldkeyId: "hmac-key-2025-12"
  newkeyId: "hmac-key-2026-01"
  oldkey: "old-hmac-secret-key-old-hmac-secret-key"
  newkey: "new-hmac-secret-key-new-hmac-secret-key"
jwt:
  secret: "new-access-secret-key-new-access-secret-key"
  expiration-ms: 86400000
  issuer: "my-auth-service"
clienthmac:
  oldkeyId: "697ece4ca0c82f1bf121b403"
  newkeyId: "697ece65a0c82f1bf121b404"
  oldkey: "old-hmac-secret-key-old-hmac-secret-key"
  newkey: "new-hmac-secret-key-new-hmac-secret-key"
grpc:
  client:
    password-encoding-service:
      address: "static://localhost:9000"
      negotiation-type: plaintext
logging:
  level:
    root: INFO
    one.org.security: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.server.authorization: TRACE
    org.springframework.web: INFO
    org.springframework.data.mongodb.core.MongoTemplate: INFO
encryption:
  master-key: "1234567890123456"
