spring:
  application:
    name: MailStreamProcessor
  data:
    redis:
      host: localhost
      port: 6379
  kafkaConfig:
    server:
      address: localhost:19092
    consumer:
      group-id: mail-processor-group
    schema:
      registry:
        url: http://localhost:18081
    topics:
      mail: mail-topic
      sms: sms-topic
      processed-mail: processed-mail-topic
      processed-sms: processed-sms-topic
      security-event: security-event-topic
      processed-security-event: processed-security-event-topic
jwt:
  access:
    oldkeyId: "access-key-2025-12"
    newkeyId: "access-key-2026-01"
    oldkey: "old-access-secret-key-old-access-secret-key"
    newkey: "new-access-secret-key-new-access-secret-key"
  refresh:
    oldkeyId: "refresh-key-2025-12"
    newkeyId: "refresh-key-2026-01"
    oldkey: "old-refresh-secret-key-old-refresh-secret-key"
    newkey: "new-refresh-secret-key-new-refresh-secret-key"
  temp:
    oldkeyId: "temp-key-2025-12"
    newkeyId: "temp-key-2026-01"
    oldkey: "old-temp-secret-key-old-temp-secret-key"
    newkey: "new-temp-secret-key-new-temp-secret-key"
  issuer: "my-auth-service"
  accessExpiration: 60
  refreshExpiration: 60
  tempExpiration: 5
  recoveryExpiration: 15
hmac:
  oldkeyId: "hmac-key-2025-12"
  newkeyId: "hmac-key-2026-01"
  oldkey: "old-hmac-secret-key-old-hmac-secret-key"
  newkey: "new-hmac-secret-key-new-hmac-secret-key"
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

server:
  port: 10008
